baseurl = "/"
title = "IfThenBen"
copyright = "Copyright &copy; 2020 - Ben Rose"
canonifyurls = true
theme = "hugo-kiera"

paginate = 6

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true
enableRobotsTXT = true

DisqusShortname = "ifthenben"

[author]
    name = "Ben"
    github = "BenRGH"
    twitter = "KingB3n_"

[params]
    tagline = "Text, Code & The End Of Everything"
    description = "Text, Code & The End Of Everything"
    custom_css = ["/styles/custom.css"]

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5